version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/node:16

      steps:
      - checkout
      - run: npm start


workflows: 
  build_now:
    jobs: 
      - build
