version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16  # Use a Node.js image compatible with your_project
    working_directory: ~/app

    steps:
      - checkout  # Pull down your source_code
      - run:
          name: Install Dependencies
          command: npm install

      # - run:
      #     name: Build
      #     command: npm run build  # Replace with your build script if necessary

  test:
    docker:
      - image: circleci/node:16  # Use the same Node.js image as the 'build' job
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

      # - run:
      #     name: Run Tests
      #     command: npm test  # Replace with your test script if necessary

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
